{% set name = "filesdb" %}
{% set version = "2.2.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f654afa6427c8aa86bdc4d94012321b767f1a0ba60c41e5613cc1389fe69200e" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  entry_points:
    - filesdb = filesdb.__main__:main
  script:  python -m pip install . --no-deps --ignore-installed
  
requirements:
  build:
    - python >=3.4
    - pip
    - pytest-runner
  run:
    - python >=3.4

test:
  source_files:
    - test_filesdb.py
  imports:
    - filesdb
  commands:
    - pytest test_filesdb.py
  requires:
    - pytest

about:
  home: https://github.com/stilley2/filesdb
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: A simple tool for tracking files
  doc_url: 'https://github.com/stilley2/filesdb'
  dev_url: 'https://github.com/stilley2/filesdb'

extra:
  recipe-maintainers:
    - stilley2
