{% set name = "filesdb" %}
{% set version = "1.9.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "637424229739effb86d0d62fdbaa573cad8f014183a61f33e5f204112e7ed737" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - filesdb = filesdb.__init__:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  imports:
    - filesdb
  commands:
    - filesdb test
  requires:
    - pytest

about:
  home: https://github.com/stilley2/filesdb
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: A simple tool for tracking files
  doc_url: 'https://github.com/stilley2/filesdb'
  dev_url: 'https://github.com/stilley2/filesdb'

extra:
  recipe-maintainers:
    - stilley2
