{% set name = "filesdb" %}
{% set version = "2.1.4" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7030f075eee6a2c06a4b76070b6615c9fc8aee9a73b8ac6c7928d8e1fe392465" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1
  entry_points:
    - filesdb = filesdb.__main__:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  source_files:
    - test_filesdb.py
  imports:
    - filesdb
  commands:
    - pytest test_filesdb.py
  requires:
    - pytest

about:
  home: https://github.com/stilley2/filesdb
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: A simple tool for tracking files
  doc_url: 'https://github.com/stilley2/filesdb'
  dev_url: 'https://github.com/stilley2/filesdb'

extra:
  recipe-maintainers:
    - stilley2
