travis:
  secure:
    BINSTAR_TOKEN: WY/Bv12dnTMTu7OGBJJzHYc+YKrLmawEajkMLwCZ7WQho66GGl3JrNyx3uUbqI9aUQuVcI8pzKGSWLFR8j5zTI2hSSCqRrWZ7fGhzaDtpfy73JRZkOy0R7IcgBZYtVRo+VRyLzQoRBksurJjj8K1spDD29A9vCavcwTr9CwytJpxj2hcNVxdTlsL5pf6NIv7hz497Nvefw9w/Q6nNiQohUDabUzaBU0t2Ss8HbkVEyOTSXwwQk0siyiuf8MOsuhOZeX26PN/ucG8PrDUnKMkkRCvD3XJHUCgsrWtFwhf/IazXZg0QPZTYVaBRe9Z07oY/IEE7UYd1h95F0fds7g7Tx9rBkhOZYDTJg0aHZJDpgMpbD6wL2OSV8D4JEVYNMbnqMCyQUJG6s/SUzsJck/ckfOMccJaQqo2bZedOFX1h0ZT0X2H4XIBdrvgyRcmB2cd8EOeo8tc7LZnafTTPRAoSK36t7o3RCyJjlk7ewGhyun6KK6Rj2/CtQAlq43Rlad1uvzWB/hV26gFHKdBPtoh7uHQwI9Df+mvPQCEalo8qQnPQN0PKRWLrFNfNwVKzQbU35aJUH/l28HDjcAGsJ04XTUvn+OJva7q2Dgl0BLSGhTh3aKgKNSW7Bbd8YEopc9iiISpI8F3CafO2qN4l+PmbOYrxM8bCqr79u/v4SgXCl0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
