travis:
  secure:
    BINSTAR_TOKEN: oALknQY/T9nVIhXnUKygL2wpvPNFNY7ldkadOzln1SVNxH9rQYKpaqld9Rg3kJA4591zYCkvD+Nm4aATVaOkHH1QhX4WMP5VR8FeCS3+lV7bpIYuarJMqw8Rr/kRG3kNG2KVIhVo7luYAF34WSohGtV0X8bCyhhDUp8mJkstQUfnuLgKZPVrwvonCASvIpQoEYfOww83tB7KH3cn/An6Ha8XctPrKzijH4RbgxTwfnJMTt/j+qGMn6x5jwYtlXGlUf07J2bMpr9rlV7e/ny3BuycV/vV7u0E1dshk7rvs92MuxQxq9aKjy6BxRmOp3O3snUJ8w5EEHMjlkRUzUMVX0p3MUi0HUzigkyam6BqoH4B6tHGPODIkaGHSq05jpgL/WjTbXIuas9SvsxPDqeFV1tzH4lPsj18hVLXmZ8CdRlaSD8PN/zpzRlcYNaFNT/JOWP/C5T7xHlalw1zW9v4rawh2c4Pd25lMRf3szD9pvOpBoVRnblb5HRFCiC1647vkPtvoB9palsmj2WyF+g1QCnSCkpRCVmZef4iZ1DGWe6uYOvRZxJhnJwfnOtM3JoFiI+3qM7Esi9qCnIi8qPzKN31r0sVNZdJeLaQOffH5rc8HNTIuBbzawDcFiTdRXsRzbQZ/McHYdwsRPU3eVc7ejo0DoocfYR4HsDzTsTOgNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
